# heavily copied from github.com/scherso, all rights to him

name:           zmonad
version:        0.1.0
synopsis:       xmonad but z
homepage:       https://github.com/jabuxas/config-notes
author:         jabuxas
maintainer:     jabuxas
license:        BSD4
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -j -dynamic

dependencies:
  - base
  - xmonad-contrib >= 0.16

source-dirs: src
  
executables:
  xmonad:
    main: main.hs
    dependencies:
      - xmonad
      - containers
      - X11 >= 1.10
  xmobar:
    main: xmobar.hs
    dependencies:
      - xmobar
    ghc-options: -rtsopts -threaded -with-rtsopts=-N
  xmobar2:
    main: xmobar2.hs
    dependencies:
      - xmobar
    ghc-options: -rtsopts -threaded -with-rtsopts=-N
